### ISSUE TITLE
Fix code so file.check_hash module runs for sqldeveloper

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/sqldeveloper-formula#13]
Need to fix `map.jinja` and `init.sls` so supplied MD5sums are verified.  This is a regression introduced by PR #12 
```
  dl:
    skip_hashcheck: False
```

```
{% if sqldeveloper.dl.skip_hashcheck in ('None', 'False', 'false', 'FALSE') %}
  module.run:
    - name: file.check_hash
    - path: '{{ sqldeveloper.tmpdir }}/{{ pkg }}.{{ sqldeveloper.dl.suffix }}'
    - file_hash: {{ sqldeveloper.oracle.md5[ pkg ] }}
    - onchanges:
      - cmd: sqldeveloper-extract-{{ pkg }}
    - require_in:
      - archive: sqldeveloper-extract-{{ pkg }}
  {% endif %}

```
