### ISSUE TITLE
group not specified, but configured as a target for recursive

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/sqldeveloper-formula#17]
MacOS issue
```
   ID: sqldeveloper-product-conf-permissions
    Function: file.directory
        Name: /Users//messi/.sqldeveloper
      Result: False
     Comment: group not specified, but configured as a target for recursive ownership management
     Started: 22:37:09.145038
    Duration: 247.833 ms
     Changes:
              ----------
              mode:
                  0744
```
